const equipment=[['Bodyweight','🤸','No gear needed'],['Dumbbells','🏋️','Adjustable or fixed'],['Barbell','🏋️','Bar and weight plates'],['Kettlebell','🔔','One or two bells'],['Resistance bands','〰️','Loop or tube bands'],['Cable machine','⚙️','Adjustable pulley'],['Gym machines','🏗️','Selectorized machines'],['Bench','▰','Flat or adjustable']];
const exercises=[
['Push-up','Chest','Bodyweight','3 × 10–15','Intermediate','🤸'],['Incline push-up','Chest','Bench','3 × 12–15','Beginner','🤸'],['Dumbbell bench press','Chest','Dumbbells','4 × 8–12','Intermediate','🏋️'],['Barbell bench press','Chest','Barbell','4 × 6–10','Advanced','🏋️'],['Cable fly','Chest','Cable machine','3 × 12–15','Intermediate','⚙️'],['Pike push-up','Shoulders','Bodyweight','3 × 8–12','Intermediate','🤸'],['Dumbbell shoulder press','Shoulders','Dumbbells','3 × 8–12','Intermediate','🏋️'],['Band lateral raise','Shoulders','Resistance bands','3 × 15','Beginner','〰️'],['Diamond push-up','Arms','Bodyweight','3 × 8–12','Intermediate','🤸'],['Dumbbell curl','Arms','Dumbbells','3 × 10–12','Beginner','🏋️'],['Cable triceps pushdown','Arms','Cable machine','3 × 12–15','Beginner','⚙️'],['Plank','Core','Bodyweight','3 × 30–60 sec','Beginner','🤸'],['Kettlebell suitcase carry','Core','Kettlebell','3 × 30 sec','Intermediate','🔔'],['Cable wood chop','Core','Cable machine','3 × 12 / side','Intermediate','⚙️'],['Bodyweight squat','Quads','Bodyweight','4 × 15','Beginner','🤸'],['Goblet squat','Quads','Kettlebell','4 × 10–12','Intermediate','🔔'],['Barbell back squat','Quads','Barbell','4 × 6–10','Advanced','🏋️'],['Leg extension','Quads','Gym machines','3 × 12–15','Beginner','🏗️'],['Superman','Back','Bodyweight','3 × 12','Beginner','🤸'],['One-arm row','Back','Dumbbells','4 × 10 / side','Intermediate','🏋️'],['Lat pulldown','Back','Cable machine','4 × 8–12','Intermediate','⚙️'],['Glute bridge','Glutes','Bodyweight','4 × 15','Beginner','🤸'],['Romanian deadlift','Hamstrings','Barbell','4 × 8–10','Advanced','🏋️'],['Standing calf raise','Calves','Bodyweight','4 × 15–20','Beginner','🤸']];
const meals=[['Power breakfast bowl','🥣','520 kcal','32g protein'],['Chicken harvest plate','🥗','610 kcal','48g protein'],['Salmon recovery bowl','🍲','650 kcal','42g protein']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let selectedEquipment=new Set(['Bodyweight']),selectedMuscle='All',searchTerm='',difficulty='All';
let workout=JSON.parse(localStorage.getItem('formeWorkout')||'[]');
let workoutSets=JSON.parse(localStorage.getItem('formeWorkoutSets')||'{}');
let history=JSON.parse(localStorage.getItem('formeHistory')||'[]');
const saveDraft=()=>{localStorage.setItem('formeWorkout',JSON.stringify(workout));localStorage.setItem('formeWorkoutSets',JSON.stringify(workoutSets))};
function defaultSets(id){const count=parseInt(exercises[id][3])||3;return Array.from({length:count},()=>({weight:'',reps:'',done:false}))}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='workout')renderWorkout();if(id==='history')renderHistory()}
function renderEquipment(){$('#equipmentGrid').innerHTML=equipment.map(([n,i,d])=>`<button class="equipment-card ${selectedEquipment.has(n)?'selected':''}" data-equipment="${n}"><span class="icon">${i}</span><h3>${n}</h3><p>${d}</p></button>`).join('');$('#equipmentCount').textContent=selectedEquipment.size;$$('.equipment-card').forEach(c=>c.onclick=()=>{const n=c.dataset.equipment;selectedEquipment.has(n)?selectedEquipment.delete(n):selectedEquipment.add(n);if(!selectedEquipment.size)selectedEquipment.add('Bodyweight');renderEquipment()})}
function renderExercises(){const muscles=['All',...new Set(exercises.map(e=>e[1]))];$('#muscleFilters').innerHTML=muscles.map(m=>`<button class="filter ${m===selectedMuscle?'active':''}" data-muscle-filter="${m}">${m}</button>`).join('');const q=searchTerm.toLowerCase();const matches=exercises.filter(e=>selectedEquipment.has(e[2])&&(selectedMuscle==='All'||e[1]===selectedMuscle)&&(difficulty==='All'||e[4]===difficulty)&&(!q||e.slice(0,5).join(' ').toLowerCase().includes(q)));$('#matchSummary').textContent=`${matches.length} matches using ${[...selectedEquipment].join(', ')}`;$('#exerciseHeading').textContent=selectedMuscle==='All'?'Exercise library':`${selectedMuscle} exercises`;$('#exerciseGrid').innerHTML=matches.length?matches.map(e=>{const id=exercises.indexOf(e),added=workout.includes(id);return `<article class="exercise-card"><div class="exercise-art"><b>${e[1]}</b><span>${e[5]}</span></div><div class="card-body"><h3>${e[0]}</h3><div class="meta"><span>${e[2]}</span><span>${e[4]}</span></div><div class="card-actions"><strong>${e[3]}</strong><button class="add-btn ${added?'added':''}" data-add="${id}">${added?'✓ Added':'+ Add'}</button></div></div></article>`}).join(''):`<div class="empty-state"><h3>No matching exercises</h3><p>Try a different search, level, muscle, or equipment selection.</p></div>`;$$('[data-muscle-filter]').forEach(b=>b.onclick=()=>{selectedMuscle=b.dataset.muscleFilter;renderExercises()});$$('[data-add]').forEach(b=>b.onclick=()=>toggleWorkout(+b.dataset.add))}
function toggleWorkout(id){if(workout.includes(id)){workout=workout.filter(x=>x!==id);delete workoutSets[id]}else{workout.push(id);workoutSets[id]=defaultSets(id)}saveDraft();renderExercises();toast(workout.includes(id)?'Added to today’s workout':'Removed from workout')}
function renderWorkout(){$('#todayLabel').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date())+' · Log every set, then save.';$('#workoutEmpty').style.display=workout.length?'none':'block';$('#saveSessionBar').classList.toggle('visible',!!workout.length);$('#workoutList').innerHTML=workout.map(id=>{const e=exercises[id];if(!workoutSets[id])workoutSets[id]=defaultSets(id);return `<article class="workout-row"><div><h3>${e[0]}</h3><p>${e[1]} · ${e[2]}</p></div><div class="set-table"><div class="set-line"><span>SET</span><span>WEIGHT (LB)</span><span>REPS</span><span>✓</span></div>${workoutSets[id].map((s,i)=>`<div class="set-line"><span>${i+1}</span><input type="number" min="0" inputmode="decimal" data-set-field="weight" data-id="${id}" data-set="${i}" value="${s.weight}" placeholder="0"><input type="number" min="0" inputmode="numeric" data-set-field="reps" data-id="${id}" data-set="${i}" value="${s.reps}" placeholder="0"><input type="checkbox" data-set-field="done" data-id="${id}" data-set="${i}" ${s.done?'checked':''}></div>`).join('')}<button class="add-set" data-add-set="${id}">＋ Add set</button></div><button class="remove" data-remove="${id}" aria-label="Remove ${e[0]}">✕</button></article>`}).join('');bindSetControls();updateSessionSummary();saveDraft()}
function bindSetControls(){$$('[data-set-field]').forEach(input=>input.onchange=()=>{const {id,set,setField}=input.dataset;workoutSets[id][+set][setField]=setField==='done'?input.checked:input.value;saveDraft();updateSessionSummary()});$$('[data-add-set]').forEach(b=>b.onclick=()=>{workoutSets[b.dataset.addSet].push({weight:'',reps:'',done:false});saveDraft();renderWorkout()});$$('[data-remove]').forEach(b=>b.onclick=()=>{toggleWorkout(+b.dataset.remove);renderWorkout()})}
function updateSessionSummary(){let sets=0,volume=0;Object.values(workoutSets).forEach(rows=>rows.forEach(s=>{if(s.done){sets++;volume+=(+s.weight||0)*(+s.reps||0)}}));$('#sessionSetCount').textContent=sets;$('#sessionVolume').textContent=volume.toLocaleString()}
function saveWorkout(){if(!workout.length)return;const completed=workout.flatMap(id=>(workoutSets[id]||[]).filter(s=>s.done).map(s=>({...s,exerciseId:id})));if(!completed.length){toast('Complete at least one set first');return}const entry={id:Date.now(),date:new Date().toISOString(),exerciseIds:[...workout],sets:completed,notes:$('#sessionNotes').value.trim()};history.unshift(entry);localStorage.setItem('formeHistory',JSON.stringify(history));workout=[];workoutSets={};saveDraft();$('#sessionNotes').value='';renderWorkout();renderHistory();toast('Workout saved to your history');showView('history')}
function renderHistory(){const empty=!history.length;$('#historyEmpty').style.display=empty?'block':'none';$('#historyList').style.display=empty?'none':'grid';const totalSets=history.reduce((n,h)=>n+h.sets.length,0),totalVolume=history.reduce((n,h)=>n+h.sets.reduce((v,s)=>v+(+s.weight||0)*(+s.reps||0),0),0);$('#historyStats').innerHTML=`<div class="history-stat"><strong>${history.length}</strong><span>workouts saved</span></div><div class="history-stat"><strong>${totalSets}</strong><span>completed sets</span></div><div class="history-stat"><strong>${totalVolume.toLocaleString()}</strong><span>lb total volume</span></div>`;$('#historyList').innerHTML=history.map(h=>{const date=new Date(h.date),vol=h.sets.reduce((v,s)=>v+(+s.weight||0)*(+s.reps||0),0);return `<article class="history-card"><div class="history-card-head"><div><h3>${new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric',year:'numeric'}).format(date)}</h3><p>${h.sets.length} sets · ${vol.toLocaleString()} lb volume${h.notes?' · '+escapeHtml(h.notes):''}</p></div><span class="history-badge">${h.exerciseIds.length} exercises</span></div><div class="history-exercises">${h.exerciseIds.map(id=>`<span>${exercises[id]?.[0]||'Exercise'}</span>`).join('')}</div><button class="delete-session" data-delete-session="${h.id}">Delete session</button></article>`}).join('');$$('[data-delete-session]').forEach(b=>b.onclick=()=>{history=history.filter(h=>h.id!==+b.dataset.deleteSession);localStorage.setItem('formeHistory',JSON.stringify(history));renderHistory();toast('Session deleted')})}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
$('#nutritionGrid').innerHTML=meals.map(m=>`<article class="meal-card"><div class="meal-art">${m[1]}</div><div class="card-body"><h3>${m[0]}</h3><div class="meta"><span>${m[2]}</span><span>${m[3]}</span></div><button class="ghost">View meal</button></div></article>`).join('');
$$('.nav-link').forEach(n=>n.onclick=()=>showView(n.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('#startPlan').onclick=()=>showView('planner');$('#quickBodyweight').onclick=()=>{selectedEquipment=new Set(['Bodyweight']);selectedMuscle='All';renderExercises();showView('exercises')};$('#showExercises').onclick=()=>{selectedMuscle='All';renderExercises();showView('exercises')};$('#backToEquipment').onclick=()=>showView('planner');$('#flipBody').onclick=()=>$('#bodyWrap').classList.toggle('back');$('#exerciseSearch').oninput=e=>{searchTerm=e.target.value;renderExercises()};$('#difficultyFilter').onchange=e=>{difficulty=e.target.value;renderExercises()};$('#saveWorkout').onclick=saveWorkout;$$('.muscle').forEach(m=>m.onclick=()=>{selectedMuscle=m.dataset.muscle;$$('.muscle').forEach(x=>x.classList.remove('selected'));m.classList.add('selected');$('#bodyTip').textContent=`${selectedMuscle} selected`;renderExercises();showView('exercises')});renderEquipment();renderWorkout();renderHistory();
