const equipment=[['Bodyweight','🤸','No gear needed'],['Dumbbells','🏋️','Adjustable or fixed'],['Barbell','🏋️','Bar and weight plates'],['Kettlebell','🔔','One or two bells'],['Resistance bands','〰️','Loop or tube bands'],['Cable machine','⚙️','Adjustable pulley'],['Gym machines','🏗️','Selectorized machines'],['Bench','▰','Flat or adjustable']];
const exercises=[
['Push-up','Chest','Bodyweight','3 × 10–15','Intermediate','🤸'],['Incline push-up','Chest','Bench','3 × 12–15','Beginner','🤸'],['Dumbbell bench press','Chest','Dumbbells','4 × 8–12','Intermediate','🏋️'],['Barbell bench press','Chest','Barbell','4 × 6–10','Advanced','🏋️'],['Cable fly','Chest','Cable machine','3 × 12–15','Intermediate','⚙️'],
['Pike push-up','Shoulders','Bodyweight','3 × 8–12','Intermediate','🤸'],['Dumbbell shoulder press','Shoulders','Dumbbells','3 × 8–12','Intermediate','🏋️'],['Band lateral raise','Shoulders','Resistance bands','3 × 15','Beginner','〰️'],
['Diamond push-up','Arms','Bodyweight','3 × 8–12','Intermediate','🤸'],['Dumbbell curl','Arms','Dumbbells','3 × 10–12','Beginner','🏋️'],['Cable triceps pushdown','Arms','Cable machine','3 × 12–15','Beginner','⚙️'],
['Plank','Core','Bodyweight','3 × 30–60 sec','Beginner','🤸'],['Kettlebell suitcase carry','Core','Kettlebell','3 × 30 sec','Intermediate','🔔'],['Cable wood chop','Core','Cable machine','3 × 12 / side','Intermediate','⚙️'],
['Bodyweight squat','Quads','Bodyweight','4 × 15','Beginner','🤸'],['Goblet squat','Quads','Kettlebell','4 × 10–12','Intermediate','🔔'],['Barbell back squat','Quads','Barbell','4 × 6–10','Advanced','🏋️'],['Leg extension','Quads','Gym machines','3 × 12–15','Beginner','🏗️'],
['Superman','Back','Bodyweight','3 × 12','Beginner','🤸'],['One-arm row','Back','Dumbbells','4 × 10 / side','Intermediate','🏋️'],['Lat pulldown','Back','Cable machine','4 × 8–12','Intermediate','⚙️'],
['Glute bridge','Glutes','Bodyweight','4 × 15','Beginner','🤸'],['Romanian deadlift','Hamstrings','Barbell','4 × 8–10','Advanced','🏋️'],['Standing calf raise','Calves','Bodyweight','4 × 15–20','Beginner','🤸']];
const meals=[['Power breakfast bowl','🥣','520 kcal','32g protein'],['Chicken harvest plate','🥗','610 kcal','48g protein'],['Salmon recovery bowl','🍲','650 kcal','42g protein']];
let selectedEquipment=new Set(['Bodyweight']);let selectedMuscle='All';let workout=JSON.parse(localStorage.getItem('formeWorkout')||'[]');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function showView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===id));scrollTo({top:0,behavior:'smooth'});if(id==='workout')renderWorkout()}
function renderEquipment(){$('#equipmentGrid').innerHTML=equipment.map(([n,i,d])=>`<button class="equipment-card ${selectedEquipment.has(n)?'selected':''}" data-equipment="${n}"><span class="icon">${i}</span><h3>${n}</h3><p>${d}</p></button>`).join('');$('#equipmentCount').textContent=selectedEquipment.size;$$('.equipment-card').forEach(c=>c.onclick=()=>{const n=c.dataset.equipment;selectedEquipment.has(n)?selectedEquipment.delete(n):selectedEquipment.add(n);if(!selectedEquipment.size)selectedEquipment.add('Bodyweight');renderEquipment()})}
function renderExercises(){let muscles=['All',...new Set(exercises.map(e=>e[1]))];$('#muscleFilters').innerHTML=muscles.map(m=>`<button class="filter ${m===selectedMuscle?'active':''}" data-muscle-filter="${m}">${m}</button>`).join('');let matches=exercises.filter(e=>selectedEquipment.has(e[2])&&(selectedMuscle==='All'||e[1]===selectedMuscle));$('#matchSummary').textContent=`${matches.length} matches using ${[...selectedEquipment].join(', ')}`;$('#exerciseHeading').textContent=selectedMuscle==='All'?'Exercises for you':`${selectedMuscle} exercises`;$('#exerciseGrid').innerHTML=matches.length?matches.map((e)=>{let id=exercises.indexOf(e),added=workout.includes(id);return `<article class="exercise-card"><div class="exercise-art"><b>${e[1]}</b><span>${e[5]}</span></div><div class="card-body"><h3>${e[0]}</h3><div class="meta"><span>${e[2]}</span><span>${e[4]}</span></div><div class="card-actions"><strong>${e[3]}</strong><button class="add-btn ${added?'added':''}" data-add="${id}">${added?'✓ Added':'+ Add'}</button></div></div></article>`}).join(''):`<div class="empty-state"><h3>No matches yet</h3><p>Select more equipment to unlock exercises for this muscle.</p></div>`;$$('[data-muscle-filter]').forEach(b=>b.onclick=()=>{selectedMuscle=b.dataset.muscleFilter;renderExercises()});$$('[data-add]').forEach(b=>b.onclick=()=>toggleWorkout(+b.dataset.add))}
function toggleWorkout(id){workout.includes(id)?workout=workout.filter(x=>x!==id):workout.push(id);localStorage.setItem('formeWorkout',JSON.stringify(workout));renderExercises();toast(workout.includes(id)?'Added to your workout':'Removed from workout')}
function renderWorkout(){$('#workoutEmpty').style.display=workout.length?'none':'block';$('#workoutList').innerHTML=workout.map(id=>{let e=exercises[id];return `<div class="workout-row"><div><h3>${e[0]}</h3><p>${e[1]} · ${e[2]}</p></div><strong>${e[3]}</strong><button class="remove" data-remove="${id}" aria-label="Remove ${e[0]}">✕</button></div>`}).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{toggleWorkout(+b.dataset.remove);renderWorkout()})}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
$('#nutritionGrid').innerHTML=meals.map(m=>`<article class="meal-card"><div class="meal-art">${m[1]}</div><div class="card-body"><h3>${m[0]}</h3><div class="meta"><span>${m[2]}</span><span>${m[3]}</span></div><button class="ghost">View meal</button></div></article>`).join('');
$$('.nav-link').forEach(n=>n.onclick=()=>showView(n.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('#startPlan').onclick=()=>showView('planner');$('#quickBodyweight').onclick=()=>{selectedEquipment=new Set(['Bodyweight']);selectedMuscle='All';renderExercises();showView('exercises')};$('#showExercises').onclick=()=>{selectedMuscle='All';renderExercises();showView('exercises')};$('#backToEquipment').onclick=()=>showView('planner');$('#flipBody').onclick=()=>$('#bodyWrap').classList.toggle('back');$$('.muscle').forEach(m=>m.onclick=()=>{selectedMuscle=m.dataset.muscle;$$('.muscle').forEach(x=>x.classList.remove('selected'));m.classList.add('selected');$('#bodyTip').textContent=`${selectedMuscle} selected`;renderExercises();showView('exercises')});renderEquipment();renderWorkout();
